ALTER TABLE "SiteSettings"
ADD COLUMN "footerBrand" TEXT NOT NULL DEFAULT 'IQ Bolalar',
ADD COLUMN "footerDescription" TEXT NOT NULL DEFAULT 'Bolalar uchun mantiqiy fikrlash, testlar va foydali materiallar platformasi.',
ADD COLUMN "footerPagesTitle" TEXT NOT NULL DEFAULT 'Sahifalar',
ADD COLUMN "footerContactsTitle" TEXT NOT NULL DEFAULT 'Kontakt',
ADD COLUMN "footerLinkHomeLabel" TEXT NOT NULL DEFAULT 'Bosh sahifa',
ADD COLUMN "footerLinkHomePath" TEXT NOT NULL DEFAULT '/',
ADD COLUMN "footerLinkMaterialsLabel" TEXT NOT NULL DEFAULT 'Materiallar',
ADD COLUMN "footerLinkMaterialsPath" TEXT NOT NULL DEFAULT '/materiallar',
ADD COLUMN "footerLinkQuizLabel" TEXT NOT NULL DEFAULT 'Testlar',
ADD COLUMN "footerLinkQuizPath" TEXT NOT NULL DEFAULT '/test',
ADD COLUMN "footerLinkAboutLabel" TEXT NOT NULL DEFAULT 'O''zimiz haqida',
ADD COLUMN "footerLinkAboutPath" TEXT NOT NULL DEFAULT '/o-nas',
ADD COLUMN "footerAddress" TEXT NOT NULL DEFAULT 'Toshkent shahri, Yunusobod tumani, Amir Temur ko''chasi 12',
ADD COLUMN "footerPhone" TEXT NOT NULL DEFAULT '+998 90 123 45 67',
ADD COLUMN "footerEmail" TEXT NOT NULL DEFAULT 'info@iqbolalar.uz',
ADD COLUMN "footerTelegram" TEXT,
ADD COLUMN "footerWorkingHours" TEXT,
ADD COLUMN "footerCopyright" TEXT NOT NULL DEFAULT 'IQ Bolalar. Barcha huquqlar himoyalangan.';
